### ISSUE TITLE
SSL not Supported?

### ISSUE THREAD

**Issue by Fancy2209** [AndrewPiroli/wii-curl#2]
I was trying to port the game Sonic Robo Blast 2 Kart and used this library in my attempt, however I got a bunch of SSL Errors, is this intended?

**Comment by AndrewPiroli** [comment]
I have not personally tested it, but it should. The issue is lack of a built in certificate store.
There are 2 options: you can disable certificate verification by setting CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST both to 0 everywhere curl is used in your app. Problem with this is you're not actually doing secure connections.

The correct way to do it is bring your own certificate store.
Basically what you need to do for that is get the latest CA bundle: https://curl.se/docs/caextract.html and either embed that into your build with bin2o, or put it on the SD card and open it and read it into a static buffer early on. Then in the places curl is used, add in `curl_easy_setopt(curl, CURLOPT_CAINFO_BLOB, &cacert);` (cacert being the aforementioned buffer)

I have been meaning to test this myself, I'll be able to look into it today or tomorrow and I'll add it to the sample app in this repo when I get it working.

**Comment by AndrewPiroli** [comment]
Tried it today and it looks like TLS is not working, even with a certificate bundle. I think this is a recent issue, the error references a lack of a strong entropy source. mbedTLS 2.x had a software implementation, but it was removed in 3.x which I recently updated to. I can add a basic (not secure) one, but I know the Wii has one internally, I'm just not sure how to get to it. Going to do a little research and once I get it working I'll have publish the recent curl update (8.11.0) and rebuild mbedTLS with any fixes.

**Comment by Fancy2209** [comment]
Seems the Wii's TLS is a device called /dev/net/ssl?
https://wiibrew.org/wiki//dev/net/ssl
https://wiibrew.org/wiki//dev/net/ssl/code
Edit: After reading I realized you meant an entropy source and not SSL itself, my bad

**Comment by AndrewPiroli** [comment]
Sorry that took so long, I had the correct fix a few days ago but I was testing incorrectly so I thought it wasn't working. Going to cut a new release now with curl 8.11.0 and a rebuilt mbedTLS 3.6.2. You'll need both.

You can see this commit https://github.com/AndrewPiroli/wii-curl/commit/e9d4858be882098de86bec559ab84bb721fc0274
for how doing an HTTPS request is different from regular HTTP. Basically you get the latest certificates and embed them into your app somehow, the devkitPPC environment provides a tool called bin2o to do this which is what I opted for. I think if you have a new enough compiler you can use `#embed` which is built in and basically does the same thing. Just stick the contents of that file into a curl_blob and use it everywhere curl options are being set up.

I haven't tested on a real console yet, but it seems to work well in Dolphin.

**Comment by Fancy2209** [comment]
Hey thanks for the info, I am looking into this right now but the project I am porting does not use C23 and uses cmake instead of make, any idea how I'd use bin2o there?

**Comment by AndrewPiroli** [comment]
I don't use cmake so I'm not really sure. A quick Google search didn't get much. I saw this: https://github.com/wjakob/nanogui/blob/master/resources/bin2c.cmake which looks like it works in a similar way but I don't know how to test it

**Comment by Fancy2209** [comment]
![imagem](https://github.com/user-attachments/assets/1f710149-df8b-49f2-b7dd-2d7a7705e8de)
I eneded up just using a tool to get a h file and embeded the file into the code, isn't pretty but works
